FROM ubuntu:16.04

RUN apt-get update && apt-get install -y build-essential libboost-dev libboost-program-options-dev libboost-filesystem-dev libboost-system-dev libboost-test-dev cmake libcppdb-dev

RUN mkdir -p /staging

COPY . /staging

RUN cd /staging && cmake . && make
