FROM ubuntu:22.04

RUN apt-get update && apt-get install -y sqlite3 vim

RUN apt-get update && apt-get install -y build-essential libboost-dev libboost-program-options-dev libboost-filesystem-dev libboost-system-dev libboost-test-dev cmake libcppdb-dev

RUN mkdir -p /staging
COPY . /staging

RUN cd /staging && cmake . && make

RUN bash /staging/extra/docker/sqlite/sqlite.sh
