FROM ubuntu:18.04

RUN apt-get update && apt-get install -y mysql-server vim

RUN apt-get update && apt-get install -y build-essential libboost-dev libboost-program-options-dev libboost-filesystem-dev libboost-system-dev libboost-test-dev cmake libcppdb-dev

RUN mkdir -p /var/run/mysqld && \
chown mysql.mysql /var/run/mysqld

RUN mkdir -p /staging
COPY . /staging

RUN cd /staging && cmake . && make

RUN bash /staging/extra/docker/mysql/mysqltest.sh
